EcommerceBookApp/Areas/Admin/Controllers/CompanyController.cs
using EcommerceBookApp.DataAccess;
using EcommerceBookApp.DataAccess.Repository.IRepository;
using EcommerceBookApp.Models;
using EcommerceBookApp.Models.ViewModels;
using EcommerceBookApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace EcommerceBookAppWeb.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class CompanyController : Controller
{
    private readonly IUnitOfWork _unitOW;
    


    public CompanyController(IUnitOfWork unitOW)
    {
        _unitOW = unitOW;
        
    }

    public IActionResult Index()
    {
        return View();
    }

    //GET
    public IActionResult Upsert(int? id)
    {
        Company company = new();      

        if (id == null || id == 0)
        {
            //if id is null we want to return company
            return View(company);
        }
        else
        {
            //if id is populated we will load our company
            company = _unitOW.Company.GetFirstOrDefault(u => u.Id == id);
            return View(company); // to the view we return back to the company model

            
        }
    
    }
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(Company obj, IFormFile? file)
    {

        if (ModelState.IsValid)
        {
            
            if (obj.Id == 0)
            {
                _unitOW.Company.Add(obj); // if is 0 we will add company
                TempData["success"] = "Company has been created successfully";
            }
            else
            {
                _unitOW.Company.Update(obj); //else we will update
                TempData["success"] = "Company has been updated successfully";

            }
            _unitOW.Save();

            return RedirectToAction("Index");
        }
        return View(obj);
    }

    //GET
    //public IActionResult Delete(int? id)
    ////{
    ////    if (id == null || id == 0)
    ////    {
    ////        return NotFound();
    ////    }

    ////    var CoverTypeFromDb = _unitOW.CoverType.GetFirstOrDefault(u => u.Id == id);


    ////    if (CoverTypeFromDb == null)
    ////    {
    ////        return NotFound();
    ////    }
    ////    return View(CoverTypeFromDb);
    ////}
    ////POST
    //[HttpPost, ActionName("Delete")]
    //[ValidateAntiForgeryToken]
    //public IActionResult DeletePost(int? id)
    //{
    //    var obj = _unitOW.CoverType.GetFirstOrDefault(u => u.Id == id);
    //    if (obj == null)
    //    {
    //        return NotFound();
    //    }

    //    _unitOW.CoverType.Remove(obj); //creating a method that will be pushed to database
    //    _unitOW.Save(); // pushing to database by SaveChanges command
    //    TempData["success"] = "CoverType was deleted successfully";
    //    return RedirectToAction("Index");


    //}

    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var companyList = _unitOW.Company.GetAll();
        return Json(new { data = companyList });
    }
    //POST
    [HttpDelete]
    
    public IActionResult Delete(int? id)
    {
        var obj = _unitOW.Company.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleting" });
        }


        _unitOW.Company.Remove(obj); //creating a method that will be pushed to database
        _unitOW.Save(); // pushing to database by SaveChanges command
        return Json(new { success = true, message = "Delete successful" });
        


    }
    #endregion

}

EcommerceBookApp/Areas/Admin/Controllers/ProductController.cs
using EcommerceBookApp.DataAccess;
using EcommerceBookApp.DataAccess.Repository.IRepository;
using EcommerceBookApp.Models;
using EcommerceBookApp.Models.ViewModels;
using EcommerceBookApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;

namespace EcommerceBookAppWeb.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]

public class ProductController : Controller
{
    private readonly IUnitOfWork _unitOW;
    private readonly IWebHostEnvironment _hostEnvironment;


    public ProductController(IUnitOfWork unitOW, IWebHostEnvironment hostEnvironment)
    {
        _unitOW = unitOW;
        _hostEnvironment = hostEnvironment;
    }

    public IActionResult Index()
    {
        return View();
    }

    //GET
    public IActionResult Upsert(int? id)
    {
        ProductViewModel productViewModel = new()
        {
            Product = new(),
            CatList = _unitOW.Category.GetAll().Select(i => new SelectListItem
            {

                Text = i.Name,
                Value = i.Id.ToString()
            }),
            CoverTypeList = _unitOW.CoverType.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            }),
        };


        if (id == null || id == 0)
        {
            //ViewBag.CatList = CatList;
            //ViewData["CoverTypeList"] = CoverTypeList;
            //we want to create product
            return View(productViewModel);
        }
        else
        {
            //to sie wywoluje gdy etujemy produkt z produkt listy
            productViewModel.Product = _unitOW.Product.GetFirstOrDefault(u => u.Id == id);
            return View(productViewModel);

            //return View(productViewModel);
            //update product
        }

        //return View(productViewModel);
    }
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(ProductViewModel obj, IFormFile? file)
    {

        if (ModelState.IsValid)
        {

            string wwwPath = _hostEnvironment.WebRootPath;
            if (file != null) //if file is not null, we will upload the file
            {
                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwPath, @"images\productsImg");
                var extension = Path.GetExtension(file.FileName);

                if (obj.Product.ImagePath != null)
                {
                    var oldImagePath = Path.Combine(wwwPath, obj.Product.ImagePath.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath)) //we chech if sth is in this Path if yes, remove it
                    {
                        System.IO.File.Delete(oldImagePath); //old image will be removed
                    }
                }
                //using is to upload file to product folder
                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);
                }
                obj.Product.ImagePath = @"\images\productsImg\" + fileName + extension; // after the old image was removed, here is updated
            }
            if (obj.Product.Id == 0)
            {
                _unitOW.Product.Add(obj.Product);
            }
            else
            {
                _unitOW.Product.Update(obj.Product);
            }
             //creating a method that will be pushed to database or updated
            _unitOW.Save(); // pushing to database by SaveChanges command
            TempData["success"] = "Product was updated successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    //GET
    //public IActionResult Delete(int? id)
    ////{
    ////    if (id == null || id == 0)
    ////    {
    ////        return NotFound();
    ////    }

    ////    var CoverTypeFromDb = _unitOW.CoverType.GetFirstOrDefault(u => u.Id == id);


    ////    if (CoverTypeFromDb == null)
    ////    {
    ////        return NotFound();
    ////    }
    ////    return View(CoverTypeFromDb);
    ////}
    ////POST
    //[HttpPost, ActionName("Delete")]
    //[ValidateAntiForgeryToken]
    //public IActionResult DeletePost(int? id)
    //{
    //    var obj = _unitOW.CoverType.GetFirstOrDefault(u => u.Id == id);
    //    if (obj == null)
    //    {
    //        return NotFound();
    //    }

    //    _unitOW.CoverType.Remove(obj); //creating a method that will be pushed to database
    //    _unitOW.Save(); // pushing to database by SaveChanges command
    //    TempData["success"] = "CoverType was deleted successfully";
    //    return RedirectToAction("Index");


    //}

    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var productList = _unitOW.Product.GetAll(includeProperties:"Category,CoverType");
        return Json(new { data = productList });
    }
    //POST
    [HttpDelete]
    
    public IActionResult Delete(int? id)
    {
        var obj = _unitOW.Product.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleting" });
        }

        var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImagePath.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath)) //we chech if sth is in this Path if yes, remove it
        {
            System.IO.File.Delete(oldImagePath); //old image will be removed
        }

        _unitOW.Product.Remove(obj); //creating a method that will be pushed to database
        _unitOW.Save(); // pushing to database by SaveChanges command
        return Json(new { success = true, message = "Delete successful" });
        


    }
    #endregion

}

EcommerceBookApp/Controllers/CategoryController.cs
using EcommerceBookApp.DataAccess;
using EcommerceBookApp.DataAccess.Repository.IRepository;
using EcommerceBookApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceBookApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOW;
        public CategoryController(IUnitOfWork unitOW)
        {
            _unitOW = unitOW;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objCatList = _unitOW.Category.GetAll();
            return View(objCatList);
        }
        //GET
        public IActionResult Create()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError", "The DisplayOrder cannot accept this Name, as they are the same. ");
            }
            if (ModelState.IsValid)
            {
                _unitOW.Category.Add(obj); //creating a method that will be pushed to database
                _unitOW.Save(); // pushing to database by SaveChanges command
                TempData["success"] = "Category has been made successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var categoryFromDb = _unitOW.Category.GetFirstOrDefault(u=>u.Id==id);


            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError", "The DisplayOrder cannot accept this Name, as they are the same. ");
            }
            if (ModelState.IsValid)
            {
                _unitOW.Category.Update(obj); //creating a method that will be pushed to database
                _unitOW.Save(); // pushing to database by SaveChanges command
                TempData["success"] = "Category was updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var categoryFromDb = _unitOW.Category.GetFirstOrDefault(u => u.Id == id);


            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOW.Category.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOW.Category.Remove(obj); //creating a method that will be pushed to database
            _unitOW.Save(); // pushing to database by SaveChanges command
            TempData["success"] = "Category was deleted successfully";
            return RedirectToAction("Index");

            
        }

    }
}

EcommerceBookApp/ViewComponents/ShopCartViewComponent.cs
using EcommerceBookApp.DataAccess.Repository.IRepository;
using EcommerceBookApp.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace EcommerceBookAppWeb.ViewComponents
{
    public class ShopCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShopCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            //first we check if user is log in or not using the claims identity
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
                {
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                else
                {
                    //if session is null, we neet to go database and retrieve the number of shop carts for the log in user and assign that to SD.SessionCart
                    //we want to set our session cart instead of get by:
                    HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShopCart.GetAll(u => u.AppUserId == claim.Value).ToList().Count);
                    //we were using GetAll instead of GetFirstOrDefault, as FFoD will just return one
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
            }
            // if claim is null
            else
            {
                HttpContext.Session.Clear();
                return View(0);

            }
        }
    }
}

EcommerceBookApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using EcommerceBookApp.Utility
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcommerceBookApp</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/BootSwatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/EcommerceBookApp.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    Hamsa
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">

                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                            @*<span class="visually-hidden">(current)</span>*@
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Website Management</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category List</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product List</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company List</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>

                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class=nav-link asp-area="Admin" asp-controller="Order" asp-action="Index">
                                Control Order
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class=nav-link asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShopCart")
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    @*<form class="d-flex">
                    <input class="form-control me-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - Created by Szymon
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/wnssm4sa3t01v3yszxstc22azrn7itege8kv9xxfe2214mzv/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EcommerceBookApp/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}