EcommerceBookApp/Areas/Admin/Controllers/CoverTypeController.cs
using EcommerceBookApp.DataAccess;
using EcommerceBookApp.DataAccess.Repository.IRepository;
using EcommerceBookApp.Models;
using EcommerceBookApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceBookAppWeb.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]

public class CoverTypeController : Controller
{
    private readonly IUnitOfWork _unitOW;
    public CoverTypeController(IUnitOfWork unitOW)
    {
        _unitOW = unitOW;
    }

    public IActionResult Index()
    {
        IEnumerable<CoverType> objCoverTypeList = _unitOW.CoverType.GetAll();
        return View(objCoverTypeList);
    }
    //GET
    public IActionResult Create()
    {
        return View();
    }
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(CoverType obj)
    {          
        if (ModelState.IsValid)
        {
            _unitOW.CoverType.Add(obj); //creating a method that will be pushed to database
            _unitOW.Save(); // pushing to database by SaveChanges command
            TempData["success"] = "CoverType has been made successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    //GET
    public IActionResult Edit(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        
        var CoverTypeFromDb = _unitOW.CoverType.GetFirstOrDefault(u => u.Id == id);


        if (CoverTypeFromDb == null)
        {
            return NotFound();
        }
        return View(CoverTypeFromDb);
    }
    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(CoverType obj)
    {
       
        if (ModelState.IsValid)
        {
            _unitOW.CoverType.Update(obj); //creating a method that will be pushed to database
            _unitOW.Save(); // pushing to database by SaveChanges command
            TempData["success"] = "CoverType was updated successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    //GET
    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        
        var CoverTypeFromDb = _unitOW.CoverType.GetFirstOrDefault(u => u.Id == id);


        if (CoverTypeFromDb == null)
        {
            return NotFound();
        }
        return View(CoverTypeFromDb);
    }
    //POST
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        var obj = _unitOW.CoverType.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return NotFound();
        }

        _unitOW.CoverType.Remove(obj); //creating a method that will be pushed to database
        _unitOW.Save(); // pushing to database by SaveChanges command
        TempData["success"] = "CoverType was deleted successfully";
        return RedirectToAction("Index");


    }

}

EcommerceBookApp/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-dark">Create CoverType</h2>
            <hr />
            <div asp-validation-summary="All"></div>
            <div class="mb-3">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            
            <button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
            <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
                Back to List
            </a>
        </div>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

EcommerceBookApp/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-dark">Delete CoverType</h2>
            <hr />
            @*@<div asp-validation-summary="All"></div>*@
            <div class="mb-3">
                <label asp-for="Name"></label>
                <input asp-for="Name" disabled class="form-control" />
            </div>
            
            <button type="submit" class="btn btn-danger" style="width: 150px">Delete</button>
            <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
                Back to List
            </a>
        </div>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

EcommerceBookApp/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-dark">Edit CoverType</h2>
            <hr />
            @*@<div asp-validation-summary="All"></div>*@
            <div class="mb-3">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            
            <button type="submit" class="btn btn-primary" style="width: 150px">Update</button>
            <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
                Back to List
            </a>
        </div>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

EcommerceBookApp/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";
}

<partial name="_Notification" />
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class=text-primary>Category List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="CoverType" asp-action="Create" class="btn btn-primary">
               <i class="bi bi-plus-circle"></i> &nbsp; Create New CoverType
            </a>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Category Name
                </th>               
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.Name
                    </td>                   
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="CoverType" asp-action="Edit" asp-route-id="@obj.Id"
                            class="btn btn-dark mx-2"> <i class="bi bi-pencil-fill"></i>Edit</a>
                            <a asp-controller="CoverType" asp-action="Delete" asp-route-id="@obj.Id"
                           class="btn btn-outline-danger mx-2"> <i class="bi bi-file-x-fill"></i>Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>